general:
  model_path: "C:\Users\User\Downloads\testingfyp-main\testingfyp-main\hand_posture\pretrained_models\CNN2D_ST_HandPosture\ST_pretrainedmodel_custom_dataset\ST_VL53L8CX_handposture_dataset\CNN2D_ST_HandPosture_8classes\CNN2D_ST_HandPosture_8classes.h5"
  project_name: "hand_posture"
  gpu_memory_limit: 4096  # optional but helps with GPU warnings

operation_mode: deployment

dataset:
   class_names: [None, Like, Dislike, FlatHand, Fist, Love, BreakTime, CrossHands]

preprocessing: # Mandatory
  Max_distance: 400 # Mandatory
  Min_distance: 100 # Mandatory
  Background_distance:  120 # Mandatory

tools:
  stedgeai:
    version: 9.1.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: False
  path_to_cubeIDE: C:\ST\STM32CubeIDE_1.13.2\STM32CubeIDE\stm32cubeide.exe

deployment:
  c_project_path: C:/Users/User/Documents/stm32ai-modelzoo/stm32ai_application_code/hand_posture
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32F4
    board: NUCLEO-F401RE

mlflow:
  uri: ./experiments_outputs/mlruns

hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
